"""
Comprehensive Agricultural Crop Catalog Data
Contains 68 agricultural crops across 7 major categories.
Only crops with actual trained classes in the PlantVillage MobileNetV2 model have ai_supported = True.
"""

CROPS_CATALOG = [
    # ==========================
    # CEREALS AND GRAINS (8)
    # ==========================
    {
        "name": "Rice / Paddy",
        "common_names": ["Rice", "Paddy", "Dhan", "Chawal"],
        "category": "Cereal",
        "icon": "🌾",
        "scientific_name": "Oryza sativa",
        "description": "The primary staple grain for over half the world's population, grown predominantly in flooded paddy fields.",
        "ai_supported": False,
        "common_diseases": ["Rice Blast (Magnaporthe oryzae)", "Bacterial Leaf Blight (Xanthomonas oryzae)", "Sheath Blight (Rhizoctonia solani)", "Brown Spot (Bipolaris oryzae)"],
        "health_indicators": ["Erect dark green leaves", "Uniform tiller density", "Clean golden panicles without discolored florets"],
        "growing_season": "Kharif (Monsoon) / Summer",
        "soil_requirements": "Heavy clay or clayey loam capable of holding standing water; pH 5.5 to 6.5"
    },
    {
        "name": "Wheat",
        "common_names": ["Wheat", "Gehun", "Kanak"],
        "category": "Cereal",
        "icon": "🌾",
        "scientific_name": "Triticum aestivum",
        "description": "A major cool-season cereal grass yielding grain used globally for flour, bread, and semolina.",
        "ai_supported": False,
        "common_diseases": ["Yellow/Stripe Rust (Puccinia striiformis)", "Brown/Leaf Rust (Puccinia triticina)", "Karnal Bunt (Tilletia indica)", "Powdery Mildew (Blumeria graminis)"],
        "health_indicators": ["Vigorous tillering at crown stage", "Healthy green flag leaf", "Uniform grain filling without empty glumes"],
        "growing_season": "Rabi (Winter season)",
        "soil_requirements": "Well-drained medium loam to clay loam; pH 6.0 to 7.5"
    },
    {
        "name": "Corn (Maize)",
        "common_names": ["Maize", "Corn", "Makka", "Field Corn", "Corn (Maize)"],
        "category": "Cereal",
        "icon": "🌽",
        "scientific_name": "Zea mays",
        "description": "High-yield cereal grain used extensively for human food, livestock feed, biofuel, and industrial starches.",
        "ai_supported": True,  # Supported by PlantVillage model (4 classes)
        "common_diseases": ["Cercospora Gray Leaf Spot", "Common Rust (Puccinia sorghi)", "Northern Leaf Blight (Exserohilum turcicum)", "Stalk Rot (Fusarium spp.)"],
        "health_indicators": ["Broad arched deep-green leaves", "Stout upright stalks", "Full tassel and well-fertilized ear silks"],
        "growing_season": "Kharif and Spring",
        "soil_requirements": "Deep, warm, fertile loamy soil rich in organic matter; pH 5.8 to 7.0"
    },
    {
        "name": "Barley",
        "common_names": ["Barley", "Jau"],
        "category": "Cereal",
        "icon": "🌾",
        "scientific_name": "Hordeum vulgare",
        "description": "A versatile cereal grain cultivated for malt beverages, animal fodder, and dietary health food.",
        "ai_supported": False,
        "common_diseases": ["Covered Smut (Ustilago hordei)", "Barley Net Blotch (Pyrenophora teres)", "Scald (Rhynchosporium secalis)"],
        "health_indicators": ["Uniform green tillers", "Erect awns on spikes", "Absence of net-like foliar lesions"],
        "growing_season": "Rabi (Winter)",
        "soil_requirements": "Light to medium loam; tolerant of moderate salinity; pH 6.5 to 8.0"
    },
    {
        "name": "Sorghum",
        "common_names": ["Sorghum", "Jowar", "Great Millet", "Milo"],
        "category": "Cereal",
        "icon": "🌾",
        "scientific_name": "Sorghum bicolor",
        "description": "A drought-resilient cereal grain essential for arid and semi-arid food security and cattle forage.",
        "ai_supported": False,
        "common_diseases": ["Grain Mold (Fusarium / Curvularia)", "Anthracnose (Colletotrichum sublineolum)", "Downy Mildew (Peronosclerospora sorghi)"],
        "health_indicators": ["Broad waxy leaves resisting desiccation", "Sturdy drought-hardy culm", "Compact seed panicles"],
        "growing_season": "Kharif and Rabi",
        "soil_requirements": "Tolerates clay, loam, and poor soils; pH 5.5 to 8.5"
    },
    {
        "name": "Pearl Millet",
        "common_names": ["Pearl Millet", "Bajra", "Spiked Millet"],
        "category": "Cereal",
        "icon": "🌾",
        "scientific_name": "Pennisetum glaucum",
        "description": "Highly heat and drought-tolerant millet that thrives in marginal sandy drylands with minimal inputs.",
        "ai_supported": False,
        "common_diseases": ["Downy Mildew / Green Ear (Sclerospora graminicola)", "Ergot (Claviceps fusiformis)", "Rust (Puccinia substriata)"],
        "health_indicators": ["Erect fibrous stems", "Dense cylindrical seed heads", "Clean leaf sheaths"],
        "growing_season": "Kharif (Rainfed summer)",
        "soil_requirements": "Light sandy to sandy loam soils; low moisture requirement; pH 6.0 to 8.0"
    },
    {
        "name": "Finger Millet",
        "common_names": ["Finger Millet", "Ragi", "Mandua", "African Millet"],
        "category": "Cereal",
        "icon": "🌾",
        "scientific_name": "Eleusine coracana",
        "description": "Nutrient-dense super-grain rich in dietary calcium, dietary fiber, and essential amino acids.",
        "ai_supported": False,
        "common_diseases": ["Ragi Blast (Pyricularia grisea)", "Foot Rot (Sclerotium rolfsii)", "Cercospora Leaf Spot"],
        "health_indicators": ["Finger-shaped digital panicles", "Sturdy non-lodging stems", "Uniform green tillering"],
        "growing_season": "Kharif",
        "soil_requirements": "Porous red loams and alluvial soils with good drainage; pH 5.0 to 7.5"
    },
    {
        "name": "Oats",
        "common_names": ["Oats", "Jai", "Avena"],
        "category": "Cereal",
        "icon": "🌾",
        "scientific_name": "Avena sativa",
        "description": "Nutritious grain and premium green fodder crop valued for human oatmeal and livestock forage.",
        "ai_supported": False,
        "common_diseases": ["Crown Rust (Puccinia coronata)", "Loose Smut (Ustilago avenae)", "Leaf Blotch (Pyrenophora avenae)"],
        "health_indicators": ["Bright green open-branching panicles", "Erect succulent blades", "Uniform stand establishment"],
        "growing_season": "Rabi (Winter)",
        "soil_requirements": "Moist loamy to clay loam soils with high water holding capacity; pH 5.5 to 7.0"
    },

    # ==========================
    # PULSES AND LEGUMES (10)
    # ==========================
    {
        "name": "Chickpea",
        "common_names": ["Chickpea", "Bengal Gram", "Chana", "Garbanzo"],
        "category": "Pulse",
        "icon": "🫘",
        "scientific_name": "Cicer arietinum",
        "description": "High-protein pulse crop cultivated for dry seeds (Desi and Kabuli types) and nitrogen-fixing capability.",
        "ai_supported": False,
        "common_diseases": ["Ascochyta Blight (Ascochyta rabiei)", "Fusarium Wilt (Fusarium oxysporum f. sp. ciceris)", "Dry Root Rot (Rhizoctonia bataticola)"],
        "health_indicators": ["Bushy branched canopy with glandular hairs", "Vigorous taproot nodulation", "Uniform pod set"],
        "growing_season": "Rabi",
        "soil_requirements": "Deep, well-drained loam or clay-loam without waterlogging; pH 6.0 to 8.0"
    },
    {
        "name": "Pigeon Pea",
        "common_names": ["Pigeon Pea", "Red Gram", "Arhar", "Tur"],
        "category": "Pulse",
        "icon": "🫘",
        "scientific_name": "Cajanus cajan",
        "description": "Perennial/annual legume that provides dietary protein (Dal) and enhances soil fertility via deep root biopores.",
        "ai_supported": False,
        "common_diseases": ["Sterility Mosaic Disease (SMD)", "Fusarium Wilt (Fusarium udum)", "Phytophthora Stem Blight"],
        "health_indicators": ["Tall woody bush canopy", "Prolific yellow/orange-veined flowers", "Healthy green trifoliate leaves"],
        "growing_season": "Kharif (Long duration)",
        "soil_requirements": "Deep alluvial and black cotton soils; sensitive to waterlogging; pH 6.5 to 7.5"
    },
    {
        "name": "Green Gram",
        "common_names": ["Green Gram", "Moong", "Mung Bean", "Moong Dal"],
        "category": "Pulse",
        "icon": "🫘",
        "scientific_name": "Vigna radiata",
        "description": "Short-duration, easily digestible pulse cultivated in multiple cropping sequences.",
        "ai_supported": False,
        "common_diseases": ["Yellow Mosaic Virus (MYMV)", "Powdery Mildew (Erysiphe polygoni)", "Cercospora Leaf Spot"],
        "health_indicators": ["Uniform green canopy without chlorotic mosaic", "Abundant pendulous pods", "Vigorous nodules"],
        "growing_season": "Kharif and Summer (Zaid)",
        "soil_requirements": "Well-drained sandy loam or alluvial soil; pH 6.2 to 7.2"
    },
    {
        "name": "Black Gram",
        "common_names": ["Black Gram", "Urad", "Urad Dal", "Mash"],
        "category": "Pulse",
        "icon": "🫘",
        "scientific_name": "Vigna mungo",
        "description": "Nutrient-rich pulse with high phosphoric acid content, widely used in South Asian culinary traditions.",
        "ai_supported": False,
        "common_diseases": ["Mungbean Yellow Mosaic Virus", "Leaf Crinkle Virus", "Powdery Mildew"],
        "health_indicators": ["Hairy trifoliate leaves", "Compact prostrate to semi-erect branching", "Dark cylindrical hairy pods"],
        "growing_season": "Kharif, Spring, and Summer",
        "soil_requirements": "Loamy to heavy black cotton soils; pH 6.5 to 7.8"
    },
    {
        "name": "Lentil",
        "common_names": ["Lentil", "Masoor", "Masoor Dal"],
        "category": "Pulse",
        "icon": "🫘",
        "scientific_name": "Lens culinaris",
        "description": "Ancient lens-shaped pulse providing iron, fiber, and protein in rainfed and cool-season cropping systems.",
        "ai_supported": False,
        "common_diseases": ["Rust (Uromyces viciae-fabae)", "Wilt (Fusarium oxysporum f. sp. lentis)", "Ascochyta Blight"],
        "health_indicators": ["Feathery pinnate foliage with tendrils", "Erect slender stems", "Abundant small rhomboid pods"],
        "growing_season": "Rabi",
        "soil_requirements": "Light loams to clay soils; moderately drought tolerant; pH 6.0 to 7.5"
    },
    {
        "name": "Kidney Bean",
        "common_names": ["Kidney Bean", "Rajma", "French Bean", "Common Bean"],
        "category": "Legume",
        "icon": "🫘",
        "scientific_name": "Phaseolus vulgaris",
        "description": "High-protein legume cultivated for both green tender pods and mature large dry kidney seeds.",
        "ai_supported": False,
        "common_diseases": ["Anthracnose (Colletotrichum lindemuthianum)", "Bean Common Mosaic Virus (BCMV)", "Rust (Uromyces appendiculatus)"],
        "health_indicators": ["Lush trifoliate foliage", "Vigorous vine or bush habit", "Smooth elongated fleshy pods"],
        "growing_season": "Rabi in plains / Kharif in hills",
        "soil_requirements": "Light, friable, well-drained loam rich in organic matter; pH 5.5 to 6.5"
    },
    {
        "name": "Soybean",
        "common_names": ["Soybean", "Soya Bean", "Bhat"],
        "category": "Legume",
        "icon": "🌱",
        "scientific_name": "Glycine max",
        "description": "Major global oilseed and protein crop containing ~40% protein and ~20% edible oil.",
        "ai_supported": True,  # Supported by PlantVillage model (1 healthy class)
        "common_diseases": ["Soybean Rust (Phakopsora pachyrhizi)", "Yellow Mosaic Virus", "Frogeye Leaf Spot (Cercospora sojina)", "Pod Blight"],
        "health_indicators": ["Uniform emerald-green trifoliate leaves", "Sturdy main stem with active Bradyrhizobium nodules", "Well-filled three-seeded pods"],
        "growing_season": "Kharif",
        "soil_requirements": "Well-drained fertile loam with good organic content; pH 6.0 to 6.8"
    },
    {
        "name": "Cowpea",
        "common_names": ["Cowpea", "Lobia", "Black-eyed Pea", "Chowli"],
        "category": "Legume",
        "icon": "🫘",
        "scientific_name": "Vigna unguiculata",
        "description": "Heat and drought-tolerant warm-season legume used for tender green pods, dry beans, and green manure.",
        "ai_supported": False,
        "common_diseases": ["Cowpea Mosaic Virus", "Cercospora Leaf Spot", "Bacterial Blight (Xanthomonas vignicola)"],
        "health_indicators": ["Broad smooth leaves", "Long pendant pods", "Rapid ground-cover canopy expansion"],
        "growing_season": "Kharif and Summer",
        "soil_requirements": "Adaptable to diverse soils from sandy to heavy loam; pH 5.5 to 7.5"
    },
    {
        "name": "Peas",
        "common_names": ["Peas", "Green Pea", "Matar", "Garden Pea"],
        "category": "Legume",
        "icon": "🫛",
        "scientific_name": "Pisum sativum",
        "description": "Cool-season legume grown for sweet fresh green seeds and pods consumed worldwide.",
        "ai_supported": False,
        "common_diseases": ["Powdery Mildew (Erysiphe pisi)", "Rust (Uromyces pisi)", "Ascochyta Blight", "Fusarium Root Rot"],
        "health_indicators": ["Glaucous blue-green vine foliage with climbing tendrils", "Plump sweet pods", "White axillary blossoms"],
        "growing_season": "Rabi",
        "soil_requirements": "Well-aerated fertile silt loam; sensitive to acidity; pH 6.0 to 7.5"
    },
    {
        "name": "Groundnut / Peanut",
        "common_names": ["Groundnut", "Peanut", "Moongphali", "Monkey Nut"],
        "category": "Oilseed",
        "icon": "🥜",
        "scientific_name": "Arachis hypogaea",
        "description": "Unique subterranean legume producing oil-rich nuts developed underground after aerial flowering.",
        "ai_supported": False,
        "common_diseases": ["Tikka Leaf Spot (Cercospora arachidicola / Cercosporidium personatum)", "Rust (Puccinia arachidis)", "Collar Rot (Aspergillus niger)"],
        "health_indicators": ["Dense quadripinnate leaf canopy", "Abundant peg entry into soil", "Clean shells without pod rot"],
        "growing_season": "Kharif and Summer",
        "soil_requirements": "Light, friable sandy loam to enable easy peg penetration and clean digging; pH 6.0 to 7.0"
    },

    # ==========================
    # VEGETABLES (25)
    # ==========================
    {
        "name": "Tomato",
        "common_names": ["Tomato", "Tamatar"],
        "category": "Vegetable",
        "icon": "🍅",
        "scientific_name": "Solanum lycopersicum",
        "description": "The world's most widely grown fruit-vegetable, cultivated in open fields and protected polyhouses.",
        "ai_supported": True,  # Supported by PlantVillage model (10 classes)
        "common_diseases": ["Bacterial Spot", "Early Blight", "Late Blight", "Leaf Mold", "Septoria Leaf Spot", "Spider Mites", "Target Spot", "Yellow Leaf Curl Virus", "Mosaic Virus"],
        "health_indicators": ["Erect indeterminate or bushy determinate foliage", "Vibrant green leaflets with uniform veins", "Prolific blossom set and smooth firm fruit"],
        "growing_season": "Round the year with peak in Kharif and Rabi",
        "soil_requirements": "Deep, well-drained sandy loam or clay loam with high organic matter; pH 6.0 to 7.0"
    },
    {
        "name": "Potato",
        "common_names": ["Potato", "Aloo"],
        "category": "Vegetable",
        "icon": "🥔",
        "scientific_name": "Solanum tuberosum",
        "description": "Crucial starch tuber crop that ranks as the world's fourth most important food crop.",
        "ai_supported": True,  # Supported by PlantVillage model (3 classes)
        "common_diseases": ["Early Blight (Alternaria solani)", "Late Blight (Phytophthora infestans)", "Black Scurf (Rhizoctonia solani)", "Common Scab (Streptomyces scabies)"],
        "health_indicators": ["Lush upright dark green canopy", "Uniform tuber initiation along subterranean stolons", "Stout non-yellowed lower stems"],
        "growing_season": "Rabi (Cool temperatures 15-20°C ideal for tuberization)",
        "soil_requirements": "Loose, friable, well-aerated sandy loam rich in humus; pH 5.2 to 6.4"
    },
    {
        "name": "Onion",
        "common_names": ["Onion", "Pyaz", "Kanda"],
        "category": "Vegetable",
        "icon": "🧅",
        "scientific_name": "Allium cepa",
        "description": "Essential biennial bulb vegetable cultivated for its pungent, culinary, and medicinal qualities.",
        "ai_supported": False,
        "common_diseases": ["Purple Blotch (Alternaria porri)", "Stemphylium Leaf Blight", "Downy Mildew (Peronospora destructor)", "Basal Rot (Fusarium oxysporum)"],
        "health_indicators": ["Hollow tubular erect blue-green foliage", "Progressive neck softening at maturity", "Dense firm bulb scales"],
        "growing_season": "Kharif, Late Kharif, and Rabi",
        "soil_requirements": "Rich, friable loam to silt loam with good moisture retention; pH 6.0 to 7.0"
    },
    {
        "name": "Garlic",
        "common_names": ["Garlic", "Lahsun"],
        "category": "Vegetable",
        "icon": "🧄",
        "scientific_name": "Allium sativum",
        "description": "Aromatic bulb vegetable prized globally for culinary flavor and organosulfur therapeutic compounds.",
        "ai_supported": False,
        "common_diseases": ["Purple Blotch", "White Rot (Stromatinia cepivora)", "Downy Mildew", "Mosaic Virus"],
        "health_indicators": ["Flat ribbon-like dark green leaves", "Firm subterranean bulb clove development", "Absence of tip burning"],
        "growing_season": "Rabi",
        "soil_requirements": "Fertile, loamy, well-drained soil rich in organic matter; pH 6.0 to 7.0"
    },
    {
        "name": "Carrot",
        "common_names": ["Carrot", "Gajar"],
        "category": "Vegetable",
        "icon": "🥕",
        "scientific_name": "Daucus carota",
        "description": "Nutritious biennial root vegetable loaded with beta-carotene, vitamins, and dietary antioxidants.",
        "ai_supported": False,
        "common_diseases": ["Alternaria Leaf Blight (Alternaria dauci)", "Powdery Mildew (Erysiphe heraclei)", "Cavity Spot (Pythium spp.)"],
        "health_indicators": ["Feathery tripinnate rosette leaves", "Smooth tapered root without fork deformation", "Vibrant orange/red core"],
        "growing_season": "Rabi / Autumn",
        "soil_requirements": "Deep, loose, stone-free sandy loam to prevent root split and forking; pH 6.0 to 6.8"
    },
    {
        "name": "Radish",
        "common_names": ["Radish", "Mooli"],
        "category": "Vegetable",
        "icon": "🌱",
        "scientific_name": "Raphanus sativus",
        "description": "Fast-maturing root vegetable with crisp, pungent flesh consumed raw in salads and cooked dishes.",
        "ai_supported": False,
        "common_diseases": ["Alternaria Blight", "White Rust (Albugo candida)", "Clubroot (Plasmodiophora brassicae)"],
        "health_indicators": ["Rapidly expanding succulent root", "Erect lobed foliage", "Absence of pithiness or internal browning"],
        "growing_season": "Rabi (Year-round for Asiatic types)",
        "soil_requirements": "Light, friable, fertile loam; pH 6.0 to 6.8"
    },
    {
        "name": "Beetroot",
        "common_names": ["Beetroot", "Chukandar", "Table Beet"],
        "category": "Vegetable",
        "icon": "🌱",
        "scientific_name": "Beta vulgaris",
        "description": "Sweet, deep-ruby taproot vegetable rich in nitrates, folate, and betalain phytonutrients.",
        "ai_supported": False,
        "common_diseases": ["Cercospora Leaf Spot (Cercospora beticola)", "Downy Mildew", "Heart Rot (Boron deficiency)"],
        "health_indicators": ["Glossy purplish-green leaf blades with red petioles", "Globular smooth taproots", "Firm unblemished flesh"],
        "growing_season": "Rabi",
        "soil_requirements": "Deep, friable loams rich in organic matter; sensitive to boron deficiency; pH 6.0 to 7.2"
    },
    {
        "name": "Cabbage",
        "common_names": ["Cabbage", "Patta Gobhi", "Band Gobhi"],
        "category": "Vegetable",
        "icon": "🥬",
        "scientific_name": "Brassica oleracea var. capitata",
        "description": "Dense leafy vegetable forming compact heads, packed with vitamin C and glucosinolates.",
        "ai_supported": False,
        "common_diseases": ["Black Rot (Xanthomonas campestris pv. campestris)", "Downy Mildew (Hyaloperonospora brassicae)", "Clubroot"],
        "health_indicators": ["Firm, tightly packed, compact head", "Uniform waxy outer leaves", "Free from caterpillar frass"],
        "growing_season": "Rabi (Autumn to Winter)",
        "soil_requirements": "Well-drained sandy loam to heavy clay with high moisture holding capacity; pH 6.0 to 7.0"
    },
    {
        "name": "Cauliflower",
        "common_names": ["Cauliflower", "Phool Gobhi"],
        "category": "Vegetable",
        "icon": "🥦",
        "scientific_name": "Brassica oleracea var. botrytis",
        "description": "Cool-season cole crop grown for its compact, tender edible head (curd) of undeveloped flower buds.",
        "ai_supported": False,
        "common_diseases": ["Black Rot", "Downy Mildew", "Alternaria Leaf Spot", "Whiptail (Molybdenum deficiency)"],
        "health_indicators": ["Compact creamy-white curd covered by protective wrapper leaves", "Absence of riciness or browning"],
        "growing_season": "Late Kharif to Rabi",
        "soil_requirements": "Deep, fertile loam rich in organic matter with steady moisture; pH 6.0 to 7.0"
    },
    {
        "name": "Broccoli",
        "common_names": ["Broccoli", "Hari Gobhi"],
        "category": "Vegetable",
        "icon": "🥦",
        "scientific_name": "Brassica oleracea var. italica",
        "description": "Nutritional powerhouse cole crop featuring edible green flower heads and thick succulent stalks.",
        "ai_supported": False,
        "common_diseases": ["Black Rot", "Downy Mildew", "Alternaria Blight", "Bacterial Soft Rot"],
        "health_indicators": ["Dense dark green to purplish-green central curd", "Tight unopened flower buds", "Thick crisp central stalk"],
        "growing_season": "Rabi",
        "soil_requirements": "Rich, moist, well-drained loam with high organic compost; pH 6.0 to 6.8"
    },
    {
        "name": "Spinach",
        "common_names": ["Spinach", "Palak"],
        "category": "Vegetable",
        "icon": "🥬",
        "scientific_name": "Spinacia oleracea",
        "description": "Rapidly growing green leafy vegetable rich in dietary iron, carotenoids, and vitamin K.",
        "ai_supported": False,
        "common_diseases": ["Downy Mildew (Peronospora effusa)", "Anthracnose", "Damping Off (Pythium / Rhizoctonia)"],
        "health_indicators": ["Broad succulent dark green blades", "Absence of yellowing or bolting", "Tender non-fibrous petioles"],
        "growing_season": "Winter / Spring",
        "soil_requirements": "Fertile loam with abundant organic nitrogen; pH 6.5 to 7.0"
    },
    {
        "name": "Lettuce",
        "common_names": ["Lettuce", "Salad Patta"],
        "category": "Vegetable",
        "icon": "🥬",
        "scientific_name": "Lactuca sativa",
        "description": "Premier salad crop grown for its crisp, refreshing, low-calorie leaves (Romaine, Butterhead, Iceberg).",
        "ai_supported": False,
        "common_diseases": ["Downy Mildew (Bremia lactucae)", "Tipburn (Calcium deficiency)", "Sclerotinia Drop"],
        "health_indicators": ["Crisp tender leaves with good turgor", "Unblemished leaf margins without necrosis", "Firm head/rosette"],
        "growing_season": "Cool season / Protected cultivation",
        "soil_requirements": "Humus-rich sandy loam with consistent moisture and excellent drainage; pH 6.0 to 6.8"
    },
    {
        "name": "Okra / Lady's Finger",
        "common_names": ["Okra", "Lady's Finger", "Bhindi", "Gumbo"],
        "category": "Vegetable",
        "icon": "🌱",
        "scientific_name": "Abelmoschus esculentus",
        "description": "Warm-season vegetable prized for mucilaginous tender green pods rich in dietary soluble fiber.",
        "ai_supported": False,
        "common_diseases": ["Yellow Vein Mosaic Virus (YVMV)", "Enation Leaf Curl Virus", "Powdery Mildew (Erysiphe cichoracearum)"],
        "health_indicators": ["Lush palmate lobed leaves free of yellow veins", "Tender 3-5 inch crisp pods that snap easily at the tip"],
        "growing_season": "Summer and Kharif",
        "soil_requirements": "Warm, rich, well-drained sandy loam; pH 6.0 to 6.8"
    },
    {
        "name": "Brinjal / Eggplant",
        "common_names": ["Brinjal", "Eggplant", "Aubergine", "Baingan"],
        "category": "Vegetable",
        "icon": "🍆",
        "scientific_name": "Solanum melongena",
        "description": "Warm-season solanaceous vegetable producing glossy purple, green, or white fruit used in diverse cuisines.",
        "ai_supported": False,
        "common_diseases": ["Little Leaf of Brinjal (Phytoplasma)", "Phomopsis Blight and Fruit Rot", "Bacterial Wilt (Ralstonia solanacearum)"],
        "health_indicators": ["Sturdy upright bush", "Glossy fruit skin with vibrant green calyx", "Absence of stem borers"],
        "growing_season": "Year-round (Autumn, Spring, and Summer crops)",
        "soil_requirements": "Deep, fertile, well-drained silt loam or clay loam; pH 5.5 to 6.8"
    },
    {
        "name": "Bell Pepper / Capsicum",
        "common_names": ["Bell Pepper", "Capsicum", "Shimla Mirch", "Sweet Pepper", "Pepper, bell"],
        "category": "Vegetable",
        "icon": "🫑",
        "scientific_name": "Capsicum annuum",
        "description": "High-value sweet pepper variety cultivated in open fields and modern climate-controlled greenhouses.",
        "ai_supported": True,  # Supported by PlantVillage model (2 classes)
        "common_diseases": ["Bacterial Spot (Xanthomonas euvesicatoria)", "Anthracnose (Colletotrichum spp.)", "Phytophthora Blight", "Powdery Mildew"],
        "health_indicators": ["Thick fleshy blocky 3-4 lobed fruit", "Glossy deep-green canopy without interveinal chlorosis", "Firm stem attachments"],
        "growing_season": "Rabi in plains / Spring-Summer in hills and polyhouses",
        "soil_requirements": "Well-drained sandy loam rich in organic matter; sensitive to waterlogging; pH 6.0 to 6.8"
    },
    {
        "name": "Chilli",
        "common_names": ["Chilli", "Hot Pepper", "Hari Mirch", "Mirchi", "Red Chilli"],
        "category": "Vegetable",
        "icon": "🌶️",
        "scientific_name": "Capsicum frutescens",
        "description": "Pungent spice and vegetable crop rich in capsaicin, vitamin C, and natural oleoresin colorants.",
        "ai_supported": False,
        "common_diseases": ["Chilli Leaf Curl Virus (transmitted by thrips/whiteflies)", "Anthracnose / Dieback (Colletotrichum capsici)", "Powdery Mildew"],
        "health_indicators": ["Lush upright branching canopy", "Prolific flower set", "Firm pungent pods with vibrant coloring"],
        "growing_season": "Kharif and Summer",
        "soil_requirements": "Well-drained black or red loams rich in organic compost; pH 6.5 to 7.5"
    },
    {
        "name": "Cucumber",
        "common_names": ["Cucumber", "Kheera", "Kakdi"],
        "category": "Vegetable",
        "icon": "🥒",
        "scientific_name": "Cucumis sativus",
        "description": "Refreshing vining cucurbit cultivated for crisp, hydrating fruit consumed fresh or pickled.",
        "ai_supported": False,
        "common_diseases": ["Downy Mildew (Pseudoperonospora cubensis)", "Powdery Mildew", "Cucumber Mosaic Virus (CMV)", "Anthracnose"],
        "health_indicators": ["Vigorous climbing vines with strong tendrils", "Prolific female blossoms", "Straight cylindrical crisp green fruit"],
        "growing_season": "Spring and Summer / Polyhouse round the year",
        "soil_requirements": "Warm, fertile sandy loam with high drainage capacity; pH 6.0 to 7.0"
    },
    {
        "name": "Pumpkin",
        "common_names": ["Pumpkin", "Kaddu", "Sitaphal"],
        "category": "Vegetable",
        "icon": "🎃",
        "scientific_name": "Cucurbita moschata",
        "description": "Vigorous trailing cucurbit producing large, nutrient-dense fruit rich in beta-carotene and dietary fiber.",
        "ai_supported": False,
        "common_diseases": ["Powdery Mildew", "Downy Mildew", "Mosaic Virus", "Fruit Rot"],
        "health_indicators": ["Large lobed hairy leaves", "Thick trailing stems", "Solid rind without soft sunken decay"],
        "growing_season": "Kharif and Summer",
        "soil_requirements": "Deep, fertile sandy loam with high organic manure; pH 6.0 to 7.5"
    },
    {
        "name": "Bottle Gourd",
        "common_names": ["Bottle Gourd", "Lauki", "Ghiya", "Calabash"],
        "category": "Vegetable",
        "icon": "🥒",
        "scientific_name": "Lagenaria siceraria",
        "description": "Popular warm-season trailing vegetable valued for tender, easily digestible cylindrical or round fruit.",
        "ai_supported": False,
        "common_diseases": ["Downy Mildew", "Powdery Mildew", "Anthracnose", "Mosaic Virus"],
        "health_indicators": ["Vigorous trellis vines with large white nocturnal blossoms", "Tender pale green fruit with fine pubescent hairs"],
        "growing_season": "Spring-Summer and Kharif",
        "soil_requirements": "Rich, well-drained sandy loam with good moisture holding ability; pH 6.0 to 7.0"
    },
    {
        "name": "Bitter Gourd",
        "common_names": ["Bitter Gourd", "Karela", "Balsam Pear"],
        "category": "Vegetable",
        "icon": "🥒",
        "scientific_name": "Momordica charantia",
        "description": "Medicinal and culinary cucurbit characterized by bitter-tasting ridged fruit that regulates blood glucose.",
        "ai_supported": False,
        "common_diseases": ["Downy Mildew", "Powdery Mildew", "Fusarium Wilt", "Fruit Fly (Bactrocera cucurbitae)"],
        "health_indicators": ["Deeply lobed palmate leaves", "Slender climbing stems", "Firm ridged fruit without blossom-end decay"],
        "growing_season": "Summer and Kharif",
        "soil_requirements": "Well-drained sandy loam rich in organic matter; pH 6.0 to 7.0"
    },
    {
        "name": "Ridge Gourd",
        "common_names": ["Ridge Gourd", "Turai", "Tori", "Luffa"],
        "category": "Vegetable",
        "icon": "🥒",
        "scientific_name": "Luffa acutangula",
        "description": "Vining vegetable with characteristic prominent longitudinal ribs, consumed tender as a dietary vegetable.",
        "ai_supported": False,
        "common_diseases": ["Downy Mildew", "Powdery Mildew", "Mosaic Virus"],
        "health_indicators": ["Climbing vines with prominent yellow flowers", "Straight dark-green ridged fruit", "Clean non-yellowed leaves"],
        "growing_season": "Summer and Rainy season",
        "soil_requirements": "Fertile loam with adequate organic compost and good drainage; pH 6.0 to 7.0"
    },
    {
        "name": "Ash Gourd",
        "common_names": ["Ash Gourd", "Petha", "Winter Melon", "Wax Gourd"],
        "category": "Vegetable",
        "icon": "🍈",
        "scientific_name": "Benincasa hispida",
        "description": "Large cucurbit whose mature fruit is coated with protective white chalky wax, providing exceptional shelf-life.",
        "ai_supported": False,
        "common_diseases": ["Downy Mildew", "Powdery Mildew", "Fruit Rot (Pythium spp.)"],
        "health_indicators": ["Broad serrated leaves", "Thick rambling vines", "Waxy white bloom over mature melon rind"],
        "growing_season": "Kharif and Summer",
        "soil_requirements": "Warm sandy loam to rich silt loam; pH 6.0 to 7.5"
    },
    {
        "name": "Drumstick / Moringa",
        "common_names": ["Drumstick", "Moringa", "Sahjan", "Horseradish Tree"],
        "category": "Vegetable",
        "icon": "🌿",
        "scientific_name": "Moringa oleifera",
        "description": "Fast-growing miracle tree producing nutrient-dense leaves and tender elongated pods with exceptional micronutrients.",
        "ai_supported": False,
        "common_diseases": ["Pod Rot (Diplodia spp.)", "Twig Canker", "Root Rot"],
        "health_indicators": ["Tripinnate feathery leaves", "Dense clusters of white blossoms", "Long tender green non-fibrous pods"],
        "growing_season": "Perennial (Flowers twice a year)",
        "soil_requirements": "Sandy or loamy well-drained soil; highly drought-hardy; pH 6.2 to 7.6"
    },
    {
        "name": "Sweet Potato",
        "common_names": ["Sweet Potato", "Shakarkand"],
        "category": "Root Crop",
        "icon": "🍠",
        "scientific_name": "Ipomoea batatas",
        "description": "Dicotyledonous root vegetable providing energy, dietary fiber, beta-carotene, and essential minerals.",
        "ai_supported": False,
        "common_diseases": ["Black Rot (Ceratocystis fimbriata)", "Scurf (Monilochaetes infuscans)", "Sweet Potato Feathery Mottle Virus"],
        "health_indicators": ["Dense ground-covering heart-shaped vines", "Absence of sweet potato weevil borers", "Uniform smooth roots"],
        "growing_season": "Kharif and Rabi",
        "soil_requirements": "Loose, friable sandy loam to enable tuber expansion; pH 5.6 to 6.6"
    },
    {
        "name": "Cassava / Tapioca",
        "common_names": ["Cassava", "Tapioca", "Yuca", "Manioc", "Sabudana Root"],
        "category": "Root Crop",
        "icon": "🥔",
        "scientific_name": "Manihot esculenta",
        "description": "Hardy woody shrub yielding large starchy tuberous roots that serve as a crucial tropical caloric staple.",
        "ai_supported": False,
        "common_diseases": ["Cassava Mosaic Disease (CMD)", "Cassava Brown Streak Disease", "Bacterial Blight (Xanthomonas axonopodis)"],
        "health_indicators": ["Erect woody canes with palmate compound leaves", "Clean white leaf veins", "Firm dense starch tubers"],
        "growing_season": "Year-round in humid tropics",
        "soil_requirements": "Deep, light, well-drained loams; tolerates low fertility; pH 5.0 to 6.5"
    },

    # ==========================
    # FRUITS (13 + 4 model fruits = 17)
    # ==========================
    {
        "name": "Banana",
        "common_names": ["Banana", "Kela", "Plantain"],
        "category": "Fruit",
        "icon": "🍌",
        "scientific_name": "Musa acuminata",
        "description": "Giant herbaceous perennial producing clustered hanging hands of potassium-rich sweet fruit.",
        "ai_supported": False,
        "common_diseases": ["Panama Wilt (Fusarium oxysporum f. sp. cubense TR4)", "Black Sigatoka (Pseudocercospora fijiensis)", "Banana Bunchy Top Virus (BBTV)"],
        "health_indicators": ["Massive upright emerald-green paddle leaves", "Stout pseudostem", "Clean heavy bunch with healthy flower bracts"],
        "growing_season": "Year-round planting in tropics",
        "soil_requirements": "Deep, rich, well-drained loamy soil with high organic matter; sensitive to salinity; pH 6.0 to 7.5"
    },
    {
        "name": "Mango",
        "common_names": ["Mango", "Aam"],
        "category": "Fruit",
        "icon": "🥭",
        "scientific_name": "Mangifera indica",
        "description": "The 'King of Fruits', a tropical evergreen fruit tree cultivated for aromatic, sweet, luscious stone fruits.",
        "ai_supported": False,
        "common_diseases": ["Anthracnose (Colletotrichum gloeosporioides)", "Powdery Mildew (Oidium mangiferae)", "Mango Malformation", "Dieback"],
        "health_indicators": ["Dense glossy leathery evergreen canopy", "Abundant healthy panicle flowering", "Smooth fruit skin without tear staining"],
        "growing_season": "Spring flowering / Summer harvesting",
        "soil_requirements": "Deep, well-drained alluvial to lateritic soils with water table > 2m; pH 5.5 to 7.5"
    },
    {
        "name": "Papaya",
        "common_names": ["Papaya", "Papita"],
        "category": "Fruit",
        "icon": "🍈",
        "scientific_name": "Carica papaya",
        "description": "Fast-growing tropical tree-like herbaceous plant bearing sweet orange-fleshed fruit with digestive papain enzymes.",
        "ai_supported": False,
        "common_diseases": ["Papaya Ring Spot Virus (PRSV)", "Anthracnose", "Foot Rot / Stem Rot (Phytophthora / Pythium)"],
        "health_indicators": ["Erect hollow stem topped by umbrella of palmately lobed leaves", "Dense spiraling fruit set along trunk"],
        "growing_season": "Year-round in warm frost-free tropics",
        "soil_requirements": "Rich, well-drained sandy loam; extremely intolerant of waterlogging; pH 6.0 to 6.8"
    },
    {
        "name": "Guava",
        "common_names": ["Guava", "Amrood"],
        "category": "Fruit",
        "icon": "🍐",
        "scientific_name": "Psidium guajava",
        "description": "Hardy tropical and subtropical fruit tree producing vitamin C-rich fruit with aromatic pink or white pulp.",
        "ai_supported": False,
        "common_diseases": ["Guava Wilt (Fusarium oxysporum f. sp. psidii)", "Anthracnose", "Fruit Canker (Pestalotiopsis psidii)"],
        "health_indicators": ["Smooth mottled peeling bark", "Opposite elliptic leaves", "Heavy flowering on current season growth"],
        "growing_season": "Mrig Bahar (Winter harvest) and Ambe Bahar (Rainy harvest)",
        "soil_requirements": "Highly adaptable from clay to light sandy soils; tolerates pH 5.0 to 8.5"
    },
    {
        "name": "Apple",
        "common_names": ["Apple", "Seb"],
        "category": "Fruit",
        "icon": "🍎",
        "scientific_name": "Malus domestica",
        "description": "Premier temperate deciduous pome fruit tree cultivated in highland orchards with adequate winter chilling.",
        "ai_supported": True,  # Supported by PlantVillage model (4 classes)
        "common_diseases": ["Apple Scab (Venturia inaequalis)", "Black Rot (Botryosphaeria obtusa)", "Cedar Apple Rust", "Fire Blight"],
        "health_indicators": ["Clean spur foliage", "Open well-ventilated goblet canopy", "Crisp blemish-free fruit with uniform coloring"],
        "growing_season": "Temperate Spring to Autumn (harvest Aug-Oct)",
        "soil_requirements": "Deep, well-drained loam or clay-loam rich in humus; pH 6.0 to 6.8"
    },
    {
        "name": "Orange",
        "common_names": ["Orange", "Citrus", "Santra", "Sweet Orange", "Mandarin"],
        "category": "Fruit",
        "icon": "🍊",
        "scientific_name": "Citrus sinensis",
        "description": "Major evergreen citrus tree cultivated in groves for fragrant blossoms and sweet, juicy hesperidium fruit.",
        "ai_supported": True,  # Supported by PlantVillage model (1 class: Citrus Greening)
        "common_diseases": ["Citrus Greening / Huanglongbing (Candidatus Liberibacter)", "Citrus Canker (Xanthomonas citri)", "Gummosis (Phytophthora spp.)"],
        "health_indicators": ["Glossy deep-green leaves with winged petioles", "Strong bud-union without gum exudation", "Smooth round fruit"],
        "growing_season": "Perennial evergreen (Subtropical winter harvest)",
        "soil_requirements": "Deep, light, well-aerated sandy loam with water table below 1.5m; pH 6.0 to 7.5"
    },
    {
        "name": "Grapes",
        "common_names": ["Grape", "Grapes", "Angoor", "Vineyard Grape"],
        "category": "Fruit",
        "icon": "🍇",
        "scientific_name": "Vitis vinifera",
        "description": "Woody deciduous climbing vine grown on trellises for fresh table consumption, raisins, and winemaking.",
        "ai_supported": True,  # Supported by PlantVillage model (4 classes)
        "common_diseases": ["Black Rot (Guignardia bidwellii)", "Esca (Black Measles)", "Isariopsis Leaf Spot", "Downy Mildew", "Powdery Mildew"],
        "health_indicators": ["Palmate lobed vibrant leaves", "Vigorous canes supported on catch wires", "Uniform translucent berry clusters"],
        "growing_season": "Spring budbreak to Autumn harvest",
        "soil_requirements": "Well-drained gravelly, sandy loam or chalky soil; pH 6.5 to 7.5"
    },
    {
        "name": "Pomegranate",
        "common_names": ["Pomegranate", "Anaar"],
        "category": "Fruit",
        "icon": "🍎",
        "scientific_name": "Punica granatum",
        "description": "Drought-hardy deciduous shrub or small tree bearing leathery-skinned fruit filled with ruby edible arils.",
        "ai_supported": False,
        "common_diseases": ["Bacterial Blight / Oily Spot (Xanthomonas axonopodis pv. punicae)", "Anthracnose", "Wilt (Ceratocystis fimbriata)"],
        "health_indicators": ["Glossy narrow oblong leaves", "Showy bright orange-red blossoms", "Heavy spherical uncracked fruit"],
        "growing_season": "Arid to semi-arid regions (Ambe, Mrig, or Hasta Bahar)",
        "soil_requirements": "Deep loamy to light alluvial soil with excellent drainage; pH 6.5 to 7.5"
    },
    {
        "name": "Watermelon",
        "common_names": ["Watermelon", "Tarbooj"],
        "category": "Fruit",
        "icon": "🍉",
        "scientific_name": "Citrullus lanatus",
        "description": "Sprawling vine crop yielding massive sweet fruit consisting of over 91% hydrating water and lycopene.",
        "ai_supported": False,
        "common_diseases": ["Anthracnose", "Fusarium Wilt", "Gummy Stem Blight", "Downy Mildew"],
        "health_indicators": ["Pinnatifid hairy leaves", "Vigorous trailing ground runners", "Heavy melon with dried tendril and creamy ground spot"],
        "growing_season": "Summer (Zaid)",
        "soil_requirements": "Warm, light, sandy loam soil with excellent drainage; pH 6.0 to 6.8"
    },
    {
        "name": "Muskmelon",
        "common_names": ["Muskmelon", "Cantaloupe", "Kharbooja", "Sweet Melon"],
        "category": "Fruit",
        "icon": "🍈",
        "scientific_name": "Cucumis melo",
        "description": "Warm-season trailing vine cultivated for aromatic, sweet, netted-rind melons with orange or green flesh.",
        "ai_supported": False,
        "common_diseases": ["Powdery Mildew", "Downy Mildew", "Fusarium Wilt", "Cucumber Mosaic Virus"],
        "health_indicators": ["Hairy orbicular leaves", "Active female flowering", "Distinct 'full-slip' stem detachment at peak sweetness"],
        "growing_season": "Spring and Summer",
        "soil_requirements": "Warm sandy to sandy-loam soils; pH 6.0 to 7.0"
    },
    {
        "name": "Pineapple",
        "common_names": ["Pineapple", "Ananas"],
        "category": "Fruit",
        "icon": "🍍",
        "scientific_name": "Ananas comosus",
        "description": "Tropical bromeliad bearing an iconic multiple fruit formed by the coalescence of individual flowering berries.",
        "ai_supported": False,
        "common_diseases": ["Heart Rot (Phytophthora nicotianae)", "Mealybug Wilt", "Black Rot (Thielaviopsis paradoxa)"],
        "health_indicators": ["Dense rosette of stiff spiny leaves", "Stout peduncle", "Symmetrical cylinder fruit with healthy green crown"],
        "growing_season": "Humid tropics (15-18 months cycle)",
        "soil_requirements": "Sandy loam rich in organic matter; strictly acidic pH 4.5 to 5.5"
    },
    {
        "name": "Strawberry",
        "common_names": ["Strawberry"],
        "category": "Fruit",
        "icon": "🍓",
        "scientific_name": "Fragaria ananassa",
        "description": "Low-growing perennial stoloniferous herb bearing fragrant, bright red aggregate fruits.",
        "ai_supported": True,  # Supported by PlantVillage model (2 classes)
        "common_diseases": ["Leaf Scorch (Diplocarpon earlianum)", "Botrytis Gray Mold (Botrytis cinerea)", "Powdery Mildew", "Anthracnose"],
        "health_indicators": ["Trifoliate glossy leaves", "Plump aromatic red berries on raised straw mulch", "Active runner propagation"],
        "growing_season": "Winter to early Spring",
        "soil_requirements": "Slightly acidic, humus-rich, well-drained sandy loam; pH 5.5 to 6.5"
    },
    {
        "name": "Peach",
        "common_names": ["Peach", "Aadu"],
        "category": "Fruit",
        "icon": "🍑",
        "scientific_name": "Prunus persica",
        "description": "Deciduous stone fruit tree native to northwest China, yielding juicy, sweet, fuzzy drupe fruits.",
        "ai_supported": True,  # Supported by PlantVillage model (2 classes)
        "common_diseases": ["Bacterial Spot (Xanthomonas arboricola pv. pruni)", "Peach Leaf Curl (Taphrina deformans)", "Brown Rot (Monilinia fructicola)"],
        "health_indicators": ["Lanceolate glossy leaves", "Clean uncracked fruit skin", "Vigorous one-year-old fruiting shoots"],
        "growing_season": "Spring flowering / Summer harvest",
        "soil_requirements": "Deep, well-drained sandy loam or gravelly loam; pH 6.0 to 6.5"
    },
    {
        "name": "Blueberry",
        "common_names": ["Blueberry"],
        "category": "Fruit",
        "icon": "🫐",
        "scientific_name": "Vaccinium sect. Cyanococcus",
        "description": "Perennial flowering shrub with blue or purple berries loaded with anthocyanin antioxidants.",
        "ai_supported": True,  # Supported by PlantVillage model (1 healthy class)
        "common_diseases": ["Mummy Berry (Monilinia vaccinii-corymbosi)", "Botrytis Blight", "Stem Canker"],
        "health_indicators": ["Lush glossy green foliage", "Sturdy cane renewal from crown", "Plump waxy berries"],
        "growing_season": "Spring to Summer",
        "soil_requirements": "Highly acidic soil with high peat/organic content; pH 4.5 to 5.2"
    },
    {
        "name": "Cherry",
        "common_names": ["Cherry", "Sweet Cherry", "Sour Cherry"],
        "category": "Fruit",
        "icon": "🍒",
        "scientific_name": "Prunus avium",
        "description": "Temperate stone fruit tree cultivated for sweet or tart glossy red drupe fruits.",
        "ai_supported": True,  # Supported by PlantVillage model (2 classes)
        "common_diseases": ["Powdery Mildew (Podosphaera clandestina)", "Brown Rot", "Bacterial Canker (Pseudomonas syringae)"],
        "health_indicators": ["Smooth ovate foliage", "Abundant healthy spur clusters", "Plump glossy fruit without cracking"],
        "growing_season": "Temperate Spring / Summer",
        "soil_requirements": "Deep, fertile, well-drained loam; intolerant of waterlogging; pH 6.0 to 7.0"
    },
    {
        "name": "Raspberry",
        "common_names": ["Raspberry", "Red Raspberry"],
        "category": "Fruit",
        "icon": "🍓",
        "scientific_name": "Rubus idaeus",
        "description": "Perennial cane fruit yielding soft, sweet, aggregate red berries with high dietary fiber.",
        "ai_supported": True,  # Supported by PlantVillage model (1 healthy class)
        "common_diseases": ["Raspberry Cane Blight", "Spur Blight", "Phytophthora Root Rot"],
        "health_indicators": ["Vibrant green compound leaves", "Healthy primocane and floricane growth", "Clean trellis support"],
        "growing_season": "Summer to Autumn",
        "soil_requirements": "Rich, well-drained loam high in organic matter; pH 5.6 to 6.5"
    },
    {
        "name": "Squash",
        "common_names": ["Squash", "Summer Squash", "Zucchini"],
        "category": "Vegetable",
        "icon": "🎃",
        "scientific_name": "Cucurbita pepo",
        "description": "Prolific vegetable cucurbit cultivated for tender summer squash and mature storage pumpkins.",
        "ai_supported": True,  # Supported by PlantVillage model (1 class: Powdery Mildew)
        "common_diseases": ["Powdery Mildew (Podosphaera xanthii)", "Downy Mildew", "Squash Vine Borer"],
        "health_indicators": ["Large triangular broad leaves", "Stout upright or bush habit", "Prolific female blossom set"],
        "growing_season": "Spring and Summer",
        "soil_requirements": "Warm, fertile, well-drained loam with abundant compost; pH 6.0 to 6.8"
    },

    # ==========================
    # COMMERCIAL / PLANTATION / OILSEED CROPS (8)
    # ==========================
    {
        "name": "Cotton",
        "common_names": ["Cotton", "Kapas", "White Gold"],
        "category": "Commercial Crop",
        "icon": "☁️",
        "scientific_name": "Gossypium hirsutum",
        "description": "Premier natural fiber crop of global economic importance, yielding soft staple fiber and cottonseed oil.",
        "ai_supported": False,
        "common_diseases": ["Bacterial Blight / Angular Leaf Spot (Xanthomonas citri pv. malvacearum)", "Cotton Leaf Curl Virus (CLCuV)", "Fusarium Wilt", "Alternaria Leaf Spot"],
        "health_indicators": ["Deep green 3-5 lobed leaves", "Strong central stem with sympodial fruiting branches", "Clean bolls opening into fluffy white lint"],
        "growing_season": "Kharif",
        "soil_requirements": "Deep, fertile black cotton soils (Vertisols) or alluvial loam with high moisture holding capacity; pH 6.0 to 8.0"
    },
    {
        "name": "Sugarcane",
        "common_names": ["Sugarcane", "Ganna", "Eekh"],
        "category": "Commercial Crop",
        "icon": "🎋",
        "scientific_name": "Saccharum officinarum",
        "description": "Tall perennial C4 grass cultivated for sucrose-rich stalks used for sugar, jaggery, ethanol, and bagasse.",
        "ai_supported": False,
        "common_diseases": ["Red Rot (Colletotrichum falcatum)", "Smut (Sporisorium scitamineum)", "Wilt (Cephalosporium sacchari)", "Grassy Shoot Disease"],
        "health_indicators": ["Thick solid stalks with uniform internodes", "Dense dark green leaf canopy", "Clean rind without red internal discoloration"],
        "growing_season": "Annual to multi-year ratoon cycle",
        "soil_requirements": "Deep, fertile, well-drained loamy soils rich in organic matter; pH 6.5 to 7.5"
    },
    {
        "name": "Tea",
        "common_names": ["Tea", "Chai Plant", "Tea Bush"],
        "category": "Plantation Crop",
        "icon": "🍵",
        "scientific_name": "Camellia sinensis",
        "description": "Perennial evergreen plantation shrub grown in highland estates for young tender leaves used in tea brewing.",
        "ai_supported": False,
        "common_diseases": ["Blister Blight (Exobasidium vexans)", "Black Rot (Corticium theae)", "Red Rust (Cephaleuros virescens)"],
        "health_indicators": ["Two leaves and a bud flushes", "Dense pruned table plucking surface", "Deep green leathery mature foliage"],
        "growing_season": "Perennial (Plucking every 7-10 days in warm months)",
        "soil_requirements": "Deep, friable, acidic highland soils rich in organic matter; pH 4.5 to 5.5"
    },
    {
        "name": "Coffee",
        "common_names": ["Coffee", "Coffee Arabica", "Coffee Robusta"],
        "category": "Plantation Crop",
        "icon": "☕",
        "scientific_name": "Coffea arabica",
        "description": "Shade-grown tropical highland shrub producing fragrant blossoms and red cherries containing coffee beans.",
        "ai_supported": False,
        "common_diseases": ["Coffee Leaf Rust (Hemileia vastatrix)", "Coffee Berry Disease (Colletotrichum kahawae)", "Black Rot (Koleroga noxia)"],
        "health_indicators": ["Glossy dark green opposite leaves", "Abundant white blossoms at leaf nodes", "Firm plump red cherries at harvest"],
        "growing_season": "Perennial (Harvesting Nov-Jan)",
        "soil_requirements": "Deep, fertile, volcanic or loamy acidic soils with canopy shade; pH 5.0 to 6.0"
    },
    {
        "name": "Coconut",
        "common_names": ["Coconut", "Nariyal", "Kalpavriksha"],
        "category": "Plantation Crop",
        "icon": "🥥",
        "scientific_name": "Cocos nucifera",
        "description": "The 'Tree of Life', a tropical monocot palm providing tender water, copra oil, fiber coir, and building material.",
        "ai_supported": False,
        "common_diseases": ["Bud Rot (Phytophthora palmivora)", "Root (Wilt) Disease", "Stem Bleeding (Thielaviopsis paradoxa)", "Leaf Rot"],
        "health_indicators": ["Spherical crown of 30-40 radiating pinnate fronds", "Continuous heavy spathe emergence and nut set"],
        "growing_season": "Perennial palm (Harvesting every 45 days)",
        "soil_requirements": "Coastal sands, alluvial, and red loams with high aeration and water movement; pH 5.2 to 8.0"
    },
    {
        "name": "Cashew",
        "common_names": ["Cashew", "Kaju"],
        "category": "Plantation Crop",
        "icon": "🥜",
        "scientific_name": "Anacardium occidentale",
        "description": "Hardy evergreen tropical tree producing succulent cashew apples bearing outer kidney-shaped nut seeds.",
        "ai_supported": False,
        "common_diseases": ["Tea Mosquito Bug & Anthracnose Complex", "Dieback / Pink Disease", "Gummosis"],
        "health_indicators": ["Vigorous dome-shaped canopy", "Abundant terminal panicle flushes", "Firm nuts without puncture lesions"],
        "growing_season": "Summer harvest (Feb-May)",
        "soil_requirements": "Poor laterite, sandy, and red coastal soils; highly tolerant of poor soil fertility; pH 5.0 to 7.0"
    },
    {
        "name": "Sesame",
        "common_names": ["Sesame", "Til", "Gingelly"],
        "category": "Oilseed",
        "icon": "🌱",
        "scientific_name": "Sesamum indicum",
        "description": "Ancient drought-tolerant annual oilseed producing capsules packed with healthy edible oil and antioxidants.",
        "ai_supported": False,
        "common_diseases": ["Phyllody (Phytoplasma transmitted by leafhoppers)", "Bacterial Leaf Spot", "Stem and Root Rot (Macrophomina phaseolina)"],
        "health_indicators": ["Erect pubescent stem", "Axillary tubular white/purple flowers", "Dense erect seed capsules"],
        "growing_season": "Kharif and Summer",
        "soil_requirements": "Light, well-drained sandy loam; intolerant of waterlogging; pH 5.5 to 7.5"
    },
    {
        "name": "Mustard",
        "common_names": ["Mustard", "Sarson", "Rai", "Indian Mustard"],
        "category": "Oilseed",
        "icon": "🌼",
        "scientific_name": "Brassica juncea",
        "description": "Major cool-season cruciferous oilseed featuring bright yellow blossoms and pungent oil-bearing seeds.",
        "ai_supported": False,
        "common_diseases": ["White Rust (Albugo candida)", "Alternaria Blight (Alternaria brassicae)", "Downy Mildew", "Sclerotinia Stem Rot"],
        "health_indicators": ["Vibrant yellow blooming canopy", "Dense upright silique pod formation", "Sturdy non-lodging stems"],
        "growing_season": "Rabi (Winter)",
        "soil_requirements": "Light to heavy loam with good drainage; pH 6.0 to 7.5"
    }
]
